--
-- View "VIEW_WKSP_DEVOPS_OBJECTS"
--
CREATE OR REPLACE FORCE EDITIONABLE VIEW "WKSP_DEVOPS"."VIEW_WKSP_DEVOPS_OBJECTS" ("OBJECT_NAME", "SUBOBJECT_NAME", "OBJECT_ID", "DATA_OBJECT_ID", "OBJECT_TYPE", "CREATED", "LAST_DDL_TIME", "TIMESTAMP", "STATUS", "TEMPORARY", "GENERATED", "SECONDARY", "NAMESPACE", "EDITION_NAME", "SHARING", "EDITIONABLE", "ORACLE_MAINTAINED", "APPLICATION", "DEFAULT_COLLATION", "DUPLICATED", "SHARDED", "IMPORTED_OBJECT", "SYNCHRONOUS_DUPLICATED", "CREATED_APPID", "CREATED_VSNID", "MODIFIED_APPID", "MODIFIED_VSNID") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  select "OBJECT_NAME","SUBOBJECT_NAME","OBJECT_ID","DATA_OBJECT_ID","OBJECT_TYPE","CREATED","LAST_DDL_TIME","TIMESTAMP","STATUS","TEMPORARY","GENERATED","SECONDARY","NAMESPACE","EDITION_NAME","SHARING","EDITIONABLE","ORACLE_MAINTAINED","APPLICATION","DEFAULT_COLLATION","DUPLICATED","SHARDED","IMPORTED_OBJECT","SYNCHRONOUS_DUPLICATED","CREATED_APPID","CREATED_VSNID","MODIFIED_APPID","MODIFIED_VSNID"
    from user_objects
    where object_type in ('TABLE', 'VIEW', 'PACKAGE', 'PACKAGE BODY')
/